In [1]:
import numpy as np

In [38]:
e = np.identity(5)
e5 = 5 * e
a = np.linalg.det(e5)
print(np.around(a))
f = np.linalg.inv(e5)
f

3125.0


array([[0.2, 0. , 0. , 0. , 0. ],
       [0. , 0.2, 0. , 0. , 0. ],
       [0. , 0. , 0.2, 0. , 0. ],
       [0. , 0. , 0. , 0.2, 0. ],
       [0. , 0. , 0. , 0. , 0.2]])

In [36]:
A = [[1,2,3],[4,0,6],[7,8,9]]
print(A)
np.around(np.linalg.det(A), 2)

[[1, 2, 3], [4, 0, 6], [7, 8, 9]]


60.0

In [21]:
B = np.linalg.inv(A)
B

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

In [27]:
a = np.array([1, 5, 7, 9])
b = 3 * a
c = a - b
d = 0 * a
A = np.array([a, b, c, d])
A

array([[  1,   5,   7,   9],
       [  3,  15,  21,  27],
       [ -2, -10, -14, -18],
       [  0,   0,   0,   0]])

In [28]:
np.linalg.matrix_rank(A)

1

In [31]:
a = np.array([1, 5])
b = np.array([2, 8])
np.dot(a, b)

42

In [35]:
a = np.array([1, 5, 0])
b = np.array([2, 8, 7])
c = np.array([7, 1.5, 3])
P = np.array([a,b,c])
p = np.linalg.det(P)
p

228.50000000000009